spring:
  application:
    name: HIBERNATE STORAGE
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql//localhost:5432/tododb
    username: postgres
    password: mysecretpassword
  h2:
    console:
      enabled: true
  ### LIQUIBASE ###
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public
    drop-first: false
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
